readthedocs/builds/urls.py
"""URL configuration for builds app."""

from django.urls import re_path
from django.views.generic.base import RedirectView


urlpatterns = [
    re_path(
        r"^(?P<project_slug>[-\w]+)/(?P<build_pk>\d+)/$",
        RedirectView.as_view(pattern_name="builds_detail", permanent=True),
        name="old_builds_detail",
    ),
    re_path(
        r"^(?P<project_slug>[-\w]+)/$",
        RedirectView.as_view(pattern_name="builds_project_list", permanent=True),
        name="old_builds_project_list",
    ),
]

readthedocs/embed/urls.py
from django.urls import path

from .views import EmbedAPI

urlpatterns = [
    path("", EmbedAPI.as_view(), name="embed_api"),
]

readthedocs/gold/urls.py
"""Gold subscription URLs."""

from django.urls import path, re_path

from readthedocs.gold import views
from readthedocs.projects.constants import PROJECT_SLUG_REGEX

urlpatterns = [
    path(
        "",
        views.GoldSubscription.as_view(),
        name="gold_detail",
    ),
    path(
        "subscription/checkout/create/",
        views.GoldCreateCheckoutSession.as_view(),
        name="gold_checkout_create",
    ),
    path(
        "subscription/portal/",
        views.GoldSubscriptionPortal.as_view(),
        name="gold_subscription_portal",
    ),
    path("projects/", views.GoldProjectsListCreate.as_view(), name="gold_projects"),
    re_path(
        (
            r"^projects/remove/(?P<project_slug>{project_slug})/$".format(
                project_slug=PROJECT_SLUG_REGEX,
            )
        ),
        views.GoldProjectRemove.as_view(),
        name="gold_projects_remove",
    ),
]

readthedocs/urls.py
import os
from functools import reduce
from operator import add

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path, re_path
from django.views.generic.base import RedirectView, TemplateView

from readthedocs.core.views import ErrorView, HomepageView, SupportView, do_not_track
from readthedocs.search.views import GlobalSearchView

admin.autodiscover()

handler400 = ErrorView.as_view(status_code=400)
handler403 = ErrorView.as_view(status_code=403)
handler404 = ErrorView.as_view(status_code=404)
handler500 = ErrorView.as_view(status_code=500)

basic_urls = [
    path("", HomepageView.as_view(), name="homepage"),
    path("security/", TemplateView.as_view(template_name="security.html")),
    re_path(
        r"^\.well-known/security.txt$",
        TemplateView.as_view(template_name="security.txt", content_type="text/plain"),
    ),
    path("support/", SupportView.as_view(), name="support"),
    # These are redirected to from the support form
    path(
        "support/success/",
        TemplateView.as_view(template_name="support/success.html"),
        name="support_success",
    ),
    path(
        "support/error/",
        TemplateView.as_view(template_name="support/error.html"),
        name="support_error",
    ),
]

rtd_urls = [
    path("search/", GlobalSearchView.as_view(), name="search"),
    path("dashboard/", include("readthedocs.projects.urls.private")),
    path("profiles/", include("readthedocs.profiles.urls.public")),
    path("accounts/", include("readthedocs.profiles.urls.private")),
    path("accounts/", include("allauth.urls")),
    path("accounts/gold/", include("readthedocs.gold.urls")),
    path("invitations/", include("readthedocs.invitations.urls")),
    # For redirects
    path("builds/", include("readthedocs.builds.urls")),
    # Put this as a unique path for the webhook, so we don't clobber existing Stripe URL's
    path("djstripe/", include("djstripe.urls", namespace="djstripe")),
]

project_urls = [
    path("projects/", include("readthedocs.projects.urls.public")),
]


organization_urls = [
    path(
        "organizations/",
        include("readthedocs.organizations.urls.private"),
    ),
    path(
        "organizations/",
        include("readthedocs.organizations.urls.public"),
    ),
    re_path(
        r"^organizations/(?P<slug>[\w.-]+)/subscription/",
        include("readthedocs.subscriptions.urls"),
    ),
    # NOTE: This is overridden in .com to serve a real pricing page.
    path(
        "pricing/",
        RedirectView.as_view(url="https://readthedocs.org/sustainability/"),
        name="pricing",
    ),
]


api_urls = [
    path("api/v2/", include("readthedocs.api.v2.urls")),
    # Keep `search_api` at root level, so the test does not fail for other API
    path("api/v2/search/", include("readthedocs.search.api.v2.urls")),
    path("api/v3/search/", include("readthedocs.search.api.v3.urls")),
    # Deprecated
    path("api/v1/embed/", include("readthedocs.embed.urls")),
    path("api/v2/embed/", include("readthedocs.embed.urls")),
    path("api-auth/", include("rest_framework.urls", namespace="rest_framework")),
    path("api/v3/", include("readthedocs.api.v3.urls")),
    path("api/v3/embed/", include("readthedocs.embed.v3.urls")),
]

i18n_urls = [
    path("i18n/", include("django.conf.urls.i18n")),
]

admin_urls = [
    re_path(r"^admin/", admin.site.urls),
]

dnt_urls = [
    re_path(r"^\.well-known/dnt/$", do_not_track),
    # https://github.com/EFForg/dnt-guide#12-how-to-assert-dnt-compliance
    re_path(
        r"^\.well-known/dnt-policy.txt$",
        TemplateView.as_view(template_name="dnt-policy.txt", content_type="text/plain"),
    ),
]

debug_urls = []
for build_format in ("epub", "htmlzip", "json", "pdf"):
    debug_urls += static(
        settings.MEDIA_URL + build_format,
        document_root=os.path.join(settings.MEDIA_ROOT, build_format),
    )
debug_urls += [
    path(
        "style-catalog/",
        TemplateView.as_view(template_name="style_catalog.html"),
    ),
    # For testing error responses and templates
    path(
        "error/<int:status_code>/",
        ErrorView.as_view(base_path="errors/dashboard"),
    ),
    # This must come last after the build output files
    path(
        "media/<path:remainder>",
        RedirectView.as_view(url=settings.STATIC_URL + "%(remainder)s"),
        name="media-redirect",
    ),
]

# Export URLs
groups = [
    basic_urls,
    rtd_urls,
    project_urls,
    organization_urls,
    api_urls,
    i18n_urls,
]

if settings.DO_NOT_TRACK_ENABLED:
    # Include Do Not Track URLs if DNT is supported
    groups.append(dnt_urls)


if settings.READ_THE_DOCS_EXTENSIONS:
    groups.append([path("", include("readthedocsext.urls"))])

if settings.ALLOW_ADMIN:
    groups.append(admin_urls)

if settings.SHOW_DEBUG_TOOLBAR:
    import debug_toolbar

    debug_urls += [
        path("__debug__/", include(debug_toolbar.urls)),
    ]
    groups.append(debug_urls)

urlpatterns = reduce(add, groups)

readthedocs/analytics/models.py
"""Analytics modeling to help understand the projects on Read the Docs."""
import datetime
from collections import namedtuple
from urllib.parse import urlparse

from django.db import models
from django.db.models import Sum
from django.utils import timezone
from django.utils.translation import gettext_lazy as _

from readthedocs.builds.models import Version
from readthedocs.core.resolver import Resolver
from readthedocs.projects.models import Feature, Project


def _last_30_days_iter():
    """Returns iterator for previous 30 days (including today)."""
    thirty_days_ago = timezone.now().date() - timezone.timedelta(days=30)

    # this includes the current day, len() = 31
    return (thirty_days_ago + timezone.timedelta(days=n) for n in range(31))


class PageViewManager(models.Manager):

    """Manager for PageView model."""

    def register_page_view(self, project, version, filename, path, status):
        """Track page view with the given parameters."""
        # TODO: remove after the migration of duplicate records has been completed.
        if project.has_feature(Feature.DISABLE_PAGEVIEWS):
            return

        # Normalize paths to avoid duplicates.
        filename = "/" + filename.lstrip("/")
        path = "/" + path.lstrip("/")

        page_view, created = self.get_or_create(
            project=project,
            version=version,
            path=filename,
            date=timezone.now().date(),
            status=status,
            defaults={
                "view_count": 1,
                "full_path": path,
            },
        )
        if not created:
            page_view.view_count = models.F("view_count") + 1
            page_view.save(update_fields=["view_count"])
        return page_view


class PageView(models.Model):

    """PageView counts per day for a project, version, and path."""

    project = models.ForeignKey(
        Project,
        related_name="page_views",
        on_delete=models.CASCADE,
    )
    # NOTE: this could potentially be removed,
    # since isn't being used and not all page
    # views (404s) are attached to a version.
    version = models.ForeignKey(
        Version,
        verbose_name=_("Version"),
        related_name="page_views",
        on_delete=models.CASCADE,
        null=True,
    )
    path = models.CharField(
        max_length=4096,
        help_text=_("Path relative to the version."),
    )
    full_path = models.CharField(
        max_length=4096,
        help_text=_("Full path including the version and language parts."),
        null=True,
        blank=True,
    )
    view_count = models.PositiveIntegerField(default=0)
    date = models.DateField(default=datetime.date.today, db_index=True)
    status = models.PositiveIntegerField(
        default=200,
        help_text=_("HTTP status code"),
    )

    objects = PageViewManager()

    class Meta:
        unique_together = ("project", "version", "path", "date", "status")
        # Make sure we have only one record with ``version=None``.
        # https://stackoverflow.com/questions/33307892/django-unique-together-with-nullable-foreignkey.
        constraints = [
            models.UniqueConstraint(
                fields=("project", "path", "date", "status"),
                condition=models.Q(version=None),
                name="analytics_pageview_constraint_unique_without_optional",
            ),
        ]

    def __str__(self):
        return f"PageView: [{self.project.slug}] - {self.full_path or self.path} for {self.date}"

    @classmethod
    def top_viewed_pages(
        cls, project, since=None, limit=10, status=200, per_version=False
    ):
        """
        Returns top pages according to view counts.

        :param per_version: If `True`, group the results per version.

        :returns: A list of named tuples ordered by the number of views.
         Each tuple contains: path, url, and count.
        """
        # pylint: disable=too-many-locals
        if since is None:
            since = timezone.now().date() - timezone.timedelta(days=30)

        group_by = "full_path" if per_version else "path"
        queryset = (
            cls.objects.filter(project=project, date__gte=since, status=status)
            .values_list(group_by)
            .annotate(count=Sum("view_count"))
            .values_list(group_by, "count", named=True)
            .order_by("-count")[:limit]
        )

        PageViewResult = namedtuple("PageViewResult", "path, url, count")
        resolver = Resolver()
        result = []
        parsed_domain = urlparse(resolver.get_domain(project))
        default_version = project.get_default_version()
        for row in queryset:
            if not per_version:
                # If we aren't groupig by version,
                # then always link to the default version.
                url_path = resolver.resolve_path(
                    project=project,
                    version_slug=default_version,
                    filename=row.path,
                )
            else:
                url_path = row.full_path or ""
            url = parsed_domain._replace(path=url_path).geturl()
            path = row.full_path if per_version else row.path
            result.append(
                PageViewResult(
                    path=path,
                    url=url,
                    count=row.count,
                )
            )
        return result

    @classmethod
    def page_views_by_date(cls, project_slug, since=None, status=200):
        """
        Returns the total page views count for last 30 days for a particular project.

        Structure of returned data is compatible to make graphs.
        Sample returned data::
            {
                'labels': ['01 Jul', '02 Jul', '03 Jul'],
                'int_data': [150, 200, 143]
            }
        This data shows that there were 150 page views on 01 July,
        200 page views on 02 July and 143 page views on 03 July.
        """
        if since is None:
            since = timezone.now().date() - timezone.timedelta(days=30)

        queryset = (
            cls.objects.filter(
                project__slug=project_slug,
                date__gte=since,
                status=status,
            )
            .values("date")
            .annotate(total_views=Sum("view_count"))
            .order_by("date")
        )

        count_dict = dict(queryset.order_by("date").values_list("date", "total_views"))

        # This fills in any dates where there is no data
        # to make sure we have a full 30 days of dates
        count_data = [count_dict.get(date) or 0 for date in _last_30_days_iter()]

        # format the date value to a more readable form
        # Eg. `16 Jul`
        last_30_days_str = [
            timezone.datetime.strftime(date, "%d %b") for date in _last_30_days_iter()
        ]

        final_data = {
            "labels": last_30_days_str,
            "int_data": count_data,
        }

        return final_data

readthedocs/api/v2/models.py
from datetime import timedelta

from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from rest_framework_api_key.models import AbstractAPIKey, BaseAPIKeyManager

from readthedocs.projects.models import Project


class BuildAPIKeyManager(BaseAPIKeyManager):
    # pylint: disable=arguments-differ
    def create_key(self, project):
        """
        Create a new API key for a project.

        Build API keys are valid for 3 hours,
        and can be revoked at any time by hitting the /api/v2/revoke/ endpoint.
        """
        expiry_date = timezone.now() + timedelta(hours=3)
        name_max_length = self.model._meta.get_field("name").max_length
        return super().create_key(
            # Name is required, so we use the project slug for it.
            name=project.slug[:name_max_length],
            expiry_date=expiry_date,
            project=project,
        )


class BuildAPIKey(AbstractAPIKey):

    """
    API key for securely interacting with the API from the builders.

    The key is attached to a single project,
    it can be used to have write access to the API V2.
    """

    project = models.ForeignKey(
        Project,
        on_delete=models.CASCADE,
        related_name="build_api_keys",
        help_text=_("Project that this API key grants access to"),
    )

    objects = BuildAPIKeyManager()

    class Meta(AbstractAPIKey.Meta):
        verbose_name = _("Build API key")
        verbose_name_plural = _("Build API keys")

readthedocs/config/models.py
"""Models for the response of the configuration object."""

from readthedocs.config.utils import to_dict


class Base:

    """
    Base class for every configuration.

    Each inherited class should define
    its attributes in the `__slots__` attribute.

    We are using `__slots__` so we can't add more attributes by mistake,
    this is similar to a namedtuple.
    """

    def __init__(self, **kwargs):
        for name in self.__slots__:
            setattr(self, name, kwargs[name])

    def as_dict(self):
        return {name: to_dict(getattr(self, name)) for name in self.__slots__}


# TODO: rename this class to `Build`
class BuildWithOs(Base):
    __slots__ = ("os", "tools", "jobs", "apt_packages", "commands")

    def __init__(self, **kwargs):
        kwargs.setdefault("apt_packages", [])
        kwargs.setdefault("commands", [])
        super().__init__(**kwargs)


class BuildTool(Base):
    __slots__ = ("version", "full_version")


class BuildJobs(Base):

    """Object used for `build.jobs` key."""

    __slots__ = (
        "pre_checkout",
        "post_checkout",
        "pre_system_dependencies",
        "post_system_dependencies",
        "pre_create_environment",
        "post_create_environment",
        "pre_install",
        "post_install",
        "pre_build",
        "post_build",
    )

    def __init__(self, **kwargs):
        """
        Create an empty list as a default for all possible builds.jobs configs.

        This is necessary because it makes the code cleaner when we add items to these lists,
        without having to check for a dict to be created first.
        """
        for step in self.__slots__:
            kwargs.setdefault(step, [])
        super().__init__(**kwargs)


class Python(Base):
    __slots__ = ("install",)


class PythonInstallRequirements(Base):
    __slots__ = ("requirements",)


class PythonInstall(Base):
    __slots__ = (
        "path",
        "method",
        "extra_requirements",
    )


class Conda(Base):
    __slots__ = ("environment",)


class Sphinx(Base):
    __slots__ = ("builder", "configuration", "fail_on_warning")


class Mkdocs(Base):
    __slots__ = ("configuration", "fail_on_warning")


class Submodules(Base):
    __slots__ = ("include", "exclude", "recursive")


class Search(Base):
    __slots__ = ("ranking", "ignore")

readthedocs/templates/builds/build_detail.html
{% extends "projects/base_project.html" %}

{% load i18n %}
{% load privacy_tags %}
{% load static %}

{% block title %}{{ build.project.name }}{% endblock %}

{% block extra_scripts %}
  <script type="text/javascript" src="{% static 'vendor/knockout.js' %}"></script>
  <script type="text/javascript" src="{% static 'builds/js/detail.js' %}"></script>
  <script type="text/javascript">
var detail_views = require('builds/detail');
$(document).ready(function () {
    var view = detail_views.BuildDetailView.init({id: '{{ build.pk }}'});
});
  </script>
{% endblock %}

{% block extra_links %}
  <link rel="stylesheet" href="{% static 'builds/css/detail.css' %}" />
{% endblock %}

{% block project_editing %}
  {% with builds_active="active" %}
    {% include "core/project_bar.html" %}
  {% endwith %}
{% endblock %}

{% block content %}
  {% block build_detail_beta %}
    {% comment %}
      Temporary notification to point to the beta dashboard, url_beta comes from the view
    {% endcomment %}
    {% if url_switch_dashboard %}
      <div class="notifications">
        <p class="notification notification-20">
          {% blocktrans trimmed with url=url_switch_dashboard %}
            Our new beta dashboard is now available for testing!
            <a href="{{ url }}">Try viewing this build on the new dashboard</a>.
          {% endblocktrans %}
        </p>
      </div>
    {% endif %}
  {% endblock build_detail_beta %}

  <div class="build build-detail" id="build-detail">

    {% if build.state != "finished" and build.state != "cancelled" and request.user|is_admin:project %}
    <form method="post" action="{% url "builds_detail" build.version.project.slug build.pk %}">
      {% csrf_token %}
      <input type="submit" value="{% trans "Cancel build" %}">
    </form>
    {% endif %}

    <!-- Build meta data -->
    <ul class="build-meta">
      <div data-bind="visible: finished()">
        <li>
          {% trans "Completed" %}
          <span>{{ build.date|date:"N j, Y. P" }}</span>
        </li>

        <li>
          {% trans "Build took" %}
          <span data-bind="text: length">
            {{ build.length }}
          </span>
          {% trans "seconds" %}
        </li>
      </div>

      {% if build.builder and request.user.is_staff %}
        <li>
          {% trans "Built on" %}
          {{ build.builder }}
        </li>
      {% endif %}

      <div data-bind="visible: finished() && success() && docs_url">
        <li>
          <a data-bind="attr: {href: docs_url}">
            {% trans "View docs" %}
          </a>
        </li>
      </div>

      <div data-bind="visible: finished()">
        <li>
          <a href="{% url "build-detail" build.pk "txt" %}">
            {% trans "View raw" %}
          </a>
        </li>
      </div>

      {# Show rebuild button only if the version is external, active and it's the latest build for this version #}
      {# see https://github.com/readthedocs/readthedocs.org/pull/6995#issuecomment-852918969 #}
      {% if request.user|is_admin:project and build.can_rebuild %}
      <div data-bind="visible: finished()">
        <form method="post" name="rebuild_commit" action="{% url "builds_project_list" project.slug %}">
          {% csrf_token %}
            <a href="#" onclick="document.forms['rebuild_commit'].submit();">
              Rebuild this build
            </a>
            <input type="hidden" name="version_slug" value="{{ build.version.slug }}">
            <input type="hidden" name="build_pk" value="{{ build.pk }}">
        </form>
      </div>
      {% endif %}

    </ul>

    <div class="build-id">
      {% blocktrans trimmed with build_id=build.pk %}
        Build #{{ build_id }}
      {% endblocktrans %}
    </div>

    <div class="build-version">
      <span class="build-version-slug">
        {% if request.user|is_admin:project and not build.is_external and build.version %}
          <a href="{% url "project_version_detail" build.version.project.slug build.version.slug %}">{{ build.version.slug }}</a>
        {% elif build.is_external %}
          {% blocktrans with build.external_version_name as external_version_name %}
            <b>{{ external_version_name }}</b>
          {% endblocktrans %}
            #<a href="{{ build.vcs_url }}">{{ build.get_version_name }}</a>
        {% else %}
          {{ build.get_version_slug }}
        {% endif %}
      </span>
      <span class="build-commit" data-bind="visible: commit">
        {% if build.get_commit_url %}
          (<a data-bind="attr: {href: commit_url}"><span data-bind="text: commit">{{ build.commit }}</span></a>)
        {% else %}
            (<span data-bind="text: commit">{{ build.commit }}</span>)
        {% endif %}
      </span>
    </div>

    <div class="build-state">
      <span>
        <span data-bind="visible: !finished(), text: state_display"
              style="display: none;">
          {{ build.get_state_display }}
        </span>
        <img src="{% static 'core/img/loader.gif' %}"
            data-bind="visible: !finished()"
            style="display: none;" />
      </span>
      <span class="build-state-successful"
            data-bind="visible: finished() && success()"
            style="display: none;">
        {% trans "Build completed" %}
      </span>
      <span class="build-state-failed"
            data-bind="visible: finished() && !success() && !cancelled()"
            style="display: none;">
          {% trans "Build failed" %}
      </span>
      <span class="build-state-cancelled"
            data-bind="visible: finished() && !success() && cancelled()"
            style="display: none;">
        {% trans "Build cancelled" %}
      </span>
    </div>

    {% if request.user|is_admin:project %}
      {# TODO: migrate these "build ideas" to the new notification system #}
      {% if not build.success and "setup.py install" in build.commands.last.output %}
        <div class="build-ideas">
          <p>
            {% url 'projects_edit' build.project.slug as project_settings_url %}
            {% blocktrans trimmed %}
              Don't want <em>setup.py install</em> called?
              Change the <strong>Install Project</strong> setting in your <a href="{{ project_settings_url }}">project settings</a>.
            {% endblocktrans %}
          </p>
        </div>
      {% endif %}
    {% endif %}


    {% comment %}
      Show non-error notifications as "build-ideas" (e.g. "build.commands is in beta")

      This temporal until we render these notifications from the front-end.
    {% endcomment %}
    {% for notification in notifications %}
    {% if notification.get_message.type != "error" %}
    <p class="build-ideas">
      {{ notification.get_message.get_rendered_body|safe }}
    </p>
    {% endif %}
    {% endfor %}


    {% if build.output %}
      {# If we have build output, this is an old build #}
      <p>
        <button data-bind="visible: !legacy_output(), click: show_legacy_output">
          {% trans "Show full build output" %}
        </button>
      </p>

      <div data-bind="visible: legacy_output"
           style="display: none;">
        <h3>{% trans "Build Output" %}</h3>
        <pre class="build-output"><span id="build-output">{{ build.output }}</span></pre>

        {% if build.setup %}
          <h3>{% trans "Setup Output" %}</h3>
          <pre class="build-output"><span id="build-setup">{{ build.setup }}</span></pre>
        {% endif %}

        {% if build.setup_error %}
          <h3>{% trans "Environment Standard Error" %}</h3>
          <pre class="build-error"><span id="build-setup_error">{{ build.setup_error }}</span></pre>
        {% endif %}
      </div>

      {% if build.error %}
        <h3>{% trans "Build Errors" %}</h3>
        <pre class="build-error"><span id="build-error">{{ build.error }}</span></pre>
      {% endif %}

    {% else %}
      {# Show new command output if lacking build.output #}

    {% comment %}
      Show error notifications as "build-error" (e.g. "syntax error in YAML")

      This temporal until we render these notifications from the front-end.
    {% endcomment %}
    {% for notification in notifications %}
    {% if notification.get_message.type == "error" %}
    <div class="build-error">
        <h3>{{ notification.get_message.type|title }}</h3>
        <p class="build-error">{{ notification.get_message.get_rendered_body|safe }}</p>
    </div>
    {% endif %}
    {% endfor %}

      {% comment %}
      After deploying the new notification system (`Notification` model),
      we won't be populating `Build.error` field anymore and these errors won't be shown anymore.
      However, old builds will still need to render the `Build.error` message
      and that's why we are keeping this HTML + KO code here.

      In the future, we can decide fully migrate `Build.error` -> `Notification` and remove this
      block completely. Read more at
      https://github.com/readthedocs/readthedocs.org/issues/10980#issuecomment-1876785304
      {% endcomment %}
      <div class="build-error"
           data-bind="visible: error"
           style="display: none;">
        <h3>{% trans "Error" %}</h3>
        <p class="build-error"
           data-bind="text: error">
            {#
              I'd like to use ``build.error|urlize`` here, so we can have nice links.
              However, this is not possible because we are using `data-bind="text: error"`
              which means that Knockout.js will use the `.error` attribute to fill
              the content of this tag dynamically.
            #}
            {{ build.error|urlize }}
        </p>
        <p>
          {% block github_issue_link %}
            {% if issue_url %}
              {% blocktrans trimmed with url=issue_url %}
                <a href="{{ url }}">Report any build issues here</a>.
              {% endblocktrans %}
            {% endif %}
          {% endblock %}
        </p>
      </div>

      <div id="build-commands"
           class="build-command-list"
           data-bind="visible: commands, foreach: display_commands"
           style="display: none;">
        <div class="build-command"
             data-bind="css: command_status">
          <div class="build-command-run" data-bind="click: toggleCommand">
            <span data-bind="text: command"></span>
          </div>
          <div class="build-command-return"
               data-bind="visible: is_showing">
            <div class="build-command-output">
              <span data-bind="text: output"></span>
            </div>

            <div class="build-command-meta">
              <span class="build-command-time">
                {% trans "Command time:" %}
                <span data-bind="text: run_time">0</span>s
              </span>

              <span class="build-command-exit-code">
                {% trans "Return" %}:
                <span data-bind="text: exit_code"></span>
              </span>
            </div>

          </div>
        </div>
      </div>
    {% endif %}

  </div>
{% endblock %}

readthedocs/templates/builds/build_list.html
{% extends "projects/base_project.html" %}

{% load i18n %}
{% load static %}

{% load pagination_tags %}
{% load privacy_tags %}
{% load projects_tags %}

{% block title %}Builds{% endblock %}

{% block project_editing %}
    {% with builds_active="active" %}
        {% include "core/project_bar.html" %}
    {% endwith %}
{% endblock %}

{% block content %}


<div id="build_list">

        {% autopaginate build_qs 15 %}

        <!-- BEGIN builds list -->
        <div class="module">
          <div class="module-wrapper">

            {% block build_versions %}
            {% if versions and request.user|is_admin:project %}
            <div class="module-header">
              <div style="float:right;">
                <form method="post" action="{% url "builds_project_list" project.slug %}">
                  {% csrf_token %}
                  <ul class="build_a_version">
                    <li style="display: inline-block">
                      <input style="display: inline-block" type="submit" value="{% trans "Build Version:" %}">
                    </li>
                    <li style="display: inline-block">
                      <select id="id_version" name="version_slug">
                      {% for version in versions|sort_version_aware %}
                        <option value="{{ version.slug }}">{{ version.slug }}</option>
                      {% endfor %}
                      </select>
                    </li>
                  </ul>
                </form>
              </div>
            </div>
            {% endif %}
            {% endblock %}

              <h1>{% trans "Recent Builds" %}</h1>
            </div>

            <div class="module-list">
              <div class="module-list-wrapper">
                <ul>
                  {% include "core/build_list_detailed.html" %}
                </ul>
              </div>
            </div>

          </div>
        </div>
        <!-- END builds list -->

        {% paginate %}

</div>

{% endblock %}

{% comment %}

{% block extra_scripts %}
{{ block.super }}
  <script type="text/javascript" src="{% static 'javascript/build_updater.js' %}"></script>

  <script type="text/javascript">
    $(function() {
      {% for build in active_builds %}
        $('#build-{{ build.id }}').effect('highlight', {}, 3000);
        new BuildListUpdater({{ build.id }}).startPolling();
      {% endfor %}
    });
  </script>
{% endblock %}

{% endcomment %}

readthedocs/templates/builds/tag_list.html
{% extends "projects/base_project.html" %}

{% load i18n %}

{% block title %}{% trans "Popular tags" %}{% endblock %}

{% block content %}
  <ul>
  {% for tag in tag_list %}
    <li><a href="{% url "projects_tag_detail" tag.slug %}">{{ tag.name }}</a></li>
  {% endfor %}
  </ul>
{% endblock %}